// <auto-generated />
using System;
using ASI_Dotnet_API_V2.Model.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASI_DotNet_API_V2.Migrations
{
    [DbContext(typeof(ASIDBContext))]
    [Migration("20231016093301_CreationBDSeries")]
    partial class CreationBDSeries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Notation", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utl_id");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("not_note");

                    b.HasKey("UtilisateurId", "SerieId")
                        .HasName("PK_Notation_utl_id_ser_id");

                    b.HasIndex("SerieId");

                    b.ToTable("Notation", (string)null);
                });

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerieId"));

                    b.Property<int?>("AnneeCreation")
                        .HasColumnType("integer")
                        .HasColumnName("ser_anneecreation");

                    b.Property<int?>("NbEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("ser_nbepisodes");

                    b.Property<int?>("NbSaisons")
                        .HasColumnType("integer")
                        .HasColumnName("ser_nbsaisons");

                    b.Property<string>("Network")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ser_network");

                    b.Property<string>("Resume")
                        .HasColumnType("TEXT")
                        .HasColumnName("ser_resume");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ser_titre");

                    b.HasKey("SerieId")
                        .HasName("PK_Serie_ser_id");

                    b.ToTable("Serie", (string)null);
                });

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("utl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilisateurId"));

                    b.Property<string>("CodePostal")
                        .HasColumnType("char(5)")
                        .HasColumnName("utl_cp");

                    b.Property<DateTime?>("DateCreation")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("utl_datecreation");

                    b.Property<float?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("utl_latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("utl_longitude");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("utl_mail");

                    b.Property<string>("Mobile")
                        .HasColumnType("char(10)")
                        .HasColumnName("utl_mobile");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_nom");

                    b.Property<string>("Pays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("France")
                        .HasColumnName("utl_pays");

                    b.Property<string>("Prenom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_prenom");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("utl_pwd");

                    b.Property<string>("Rue")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("utl_rue");

                    b.Property<string>("Ville")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_ville");

                    b.HasKey("UtilisateurId")
                        .HasName("PK_Utilisateur_utl_id");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Notation", b =>
                {
                    b.HasOne("ASI_Dotnet_API_V2.Model.EntityFramework.Serie", "SerieNotee")
                        .WithMany("NotesSeries")
                        .HasForeignKey("SerieId")
                        .IsRequired()
                        .HasConstraintName("FK_Notation_Serie_ser_id");

                    b.HasOne("ASI_Dotnet_API_V2.Model.EntityFramework.Utilisateur", "UtilisateurNotant")
                        .WithMany("NotesUtilisateurs")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired()
                        .HasConstraintName("FK_Notation_Utilisateur_utl_id");

                    b.Navigation("SerieNotee");

                    b.Navigation("UtilisateurNotant");
                });

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Serie", b =>
                {
                    b.Navigation("NotesSeries");
                });

            modelBuilder.Entity("ASI_Dotnet_API_V2.Model.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("NotesUtilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
